### ISSUE TITLE
Don't load in last jenkins server

### ISSUE THREAD

**Issue by Asgoret** [jenkinsci/outbound-webhook-plugin#12]
Hi! After the last update module doesn't load in the last jenkins docker image based on Centos latest.
Java version:
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
Is there any way to fix it?

**UPD#1**: Jenkins doesn't support java 14.
Documentation: https://www.jenkins.io/doc/administration/requirements/java/
Error:
```

SEVERE: Running with Java class version 58 which is not in the list of supported versions: [52, 55]. Run with the --enable-future-java flag to enable such behavior. See https://jenkins.io/redirect/java-support/
--
  | java.lang.UnsupportedClassVersionError: 58.0
  | at Main.verifyJavaVersion(Main.java:174)
  | at Main.main(Main.java:142)
  |  
  | Jenkins requires Java versions [8, 11] but you are running with Java 14 from /usr/lib/jvm/java-14-openjdk-14.0.1.7-2.rolling.el8.x86_64
  | java.lang.UnsupportedClassVersionError: 58.0
  | at Main.verifyJavaVersion(Main.java:174)
  | at Main.main(Main.java:142)
```
**UPD#2**: Plugin error:
```
java.io.IOException: Failed to load: Outbound WebHook for build events (0.3.0)
 - Java (14) or higher required
```

cc @tylerlong @jamiewastin @jc21

**Comment by antonystevens20** [comment]
@Asgoret if you install JDK 14 and follow the instructions for "Run with the --enable-future-java flag" per the instructions, Jenkins does run. It appears this plugin won't run otherwise.

**Comment by tsunamaru** [comment]
A quick and dirty solution is to downgrade dependencies.
```
diff --git a/build.gradle b/build.gradle
index 67c07bf..2b42e5f 100644
--- a/build.gradle
+++ b/build.gradle
@@ -4,7 +4,7 @@ plugins {
 }
 
 group 'org.jenkins-ci.plugins'
-version '0.3.0'
+version '0.3.1'
 description 'Outbound WebHook for Jenkins build events'
 
 jenkinsPlugin {
@@ -30,6 +30,6 @@ repositories {
 }
 
 dependencies {
-    compile 'com.alibaba:fastjson:1.2.71'
-    compile 'com.squareup.okhttp3:okhttp:4.7.2'
+    compile 'com.alibaba:fastjson:1.2.34'
+    compile 'com.squareup.okhttp3:okhttp:3.8.1'
 }
```
Although it's worked for me, I didn't test it much, so use at your own peril.

**Comment by marianobenes** [comment]
Im having the same issue, is there any way to redownload an old version of the plugin?

**Comment by Asgoret** [comment]
> Im having the same issue, is there any way to redownload an old version of the plugin?

Use unsupported javas via `--enable-future-java` flag. We simply move from this plugin. Jenkins stability is a more high priority.

**Comment by tsunamaru** [comment]
@marianobenes you can download previous versions from [releases page](https://updates.jenkins.io/download/plugins/outbound-webhook/). Alternatively, you can use latest version with my patch above. Compile it by yourself or download my [precompiled .xpi](https://transfer.sh/gqwlP/outbound-webhook.hpi)  
Then simply go to Manage Plugins > Advanced > Upload plugin and click on downloaded .xpi

@Asgoret 
> Use unsupported javas via --enable-future-java flag

Very bad idea!

**Comment by Asgoret** [comment]
> @marianobenes you can download previous versions from [releases page](https://updates.jenkins.io/download/plugins/outbound-webhook/). Alternatively, you can use latest version with my patch above. Compile it by yourself or download my [precompiled .xpi](https://transfer.sh/gqwlP/outbound-webhook.hpi)
> Then simply go to Manage Plugins > Advanced > Upload plugin and click on downloaded .xpi
> 
> @Asgoret
> 
> > Use unsupported javas via --enable-future-java flag
> 
> Very bad idea!

Well... [not my](https://github.com/jenkinsci/outbound-webhook-plugin/issues/12#issuecomment-650460767) ;D

**Comment by antonystevens20** [comment]
Hey, don't blame me. That's literally the only way to get this plugin working on the latest code revision.

In other words, don't run this in production.

**Comment by Asgoret** [comment]
> Hey, don't blame me. That's literally the only way to get this plugin working on the latest code revision.
> 
> In other words, don't run this in production.

Not blaming anyone. Sorry if I offend you. As a workaround it's fine.

**Comment by vwbusguy** [comment]
Is Java 14 a hard dependency?  Is the plugin really not compatible with 8+ or was it just compiled with Java 14 without backward compatibility enabled in the compiler?

**Comment by vwbusguy** [comment]
It looks like `./gradlew build` works with Java 8, so there doesn't appear to be a good reason for the hard Java 14 requirement.  It looks like it just needs to be rebuilt and republished with backward compatibility or with jdk8.

**Comment by vwbusguy** [comment]
Here's the workaround.  From a machine with jdk8 installed (check by running `java -version` - you may need to change your alternatives if you have jdk8 installed and there's a different version reported):

- Clone this repo
- Run `./gradlew build`
- In Jenkins go to Manage Jenkins-> Manage Plugins-> Advanced-> Upload plugin
- Upload the build/libs/outbound-webhook.hpi file
- Restart Jenkins when it finishes installing

It should now be loaded successfully:
![image](https://user-images.githubusercontent.com/5474941/90668317-c28d2d00-e204-11ea-9744-03a3d11c7edc.png)

**Comment by Asgoret** [comment]
> Here's the workaround. From a machine with jdk8 installed (check by running `java -version` - you may need to change your alternatives if you have jdk8 installed and there's a different version reported):
> 
> * Clone this repo
> * Run `./gradlew build`
> * In Jenkins go to Manage Jenkins-> Manage Plugins-> Advanced-> Upload plugin
> * Upload the build/libs/outbound-webhook.hpi file
> * Restart Jenkins when it finishes installing
> 
> It should now be loaded successfully:
> ![image](https://user-images.githubusercontent.com/5474941/90668317-c28d2d00-e204-11ea-9744-03a3d11c7edc.png)

This workaroun breaks jenkins casc installations when you specify jenkins plugins via plugins installer and added several manual steps.

**Comment by vwbusguy** [comment]
That very well may be, but the plugin as it is is broken for all Jenkins installations on a supported Java version.  If the author would recompile this with a supported JDK compatibility and release a new version, it would work for everyone.

**Comment by sidyhe** [comment]
the latest docker image ``jenkins:lts`` was with java8, the plugin cannot work.

**Comment by karololszacki** [comment]
I forked this repo since its on MIT LICENSE, available here: https://github.com/karololszacki/outbound-webhook-plugin

I also compiled my changes with java8, I used steps by @vwbusguy and uploaded the hpi here:
https://github.com/karololszacki/outbound-webhook-plugin/releases/tag/0.3.1

**Comment by gheine** [comment]
Can we get an official release of @karololszacki's fix please so that we can use this plugin with the docker version of jenkins again?

**Comment by d4rky-pl** [comment]
@tylerlong any chance you could take a look? This plugin is not actively maintained (I'm guessing since it's more or less feature-complete) but it would be nice if this problem could be solved.
